// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATestServiceManager.Repositories.AnhTHQ.Models;

public partial class InvoiceMinhNDA
{
    public int InvoiceMinhNdaid { get; set; }

    public string PaymentStatus { get; set; }

    public string PaymentMethod { get; set; }

    public decimal? Amount { get; set; }

    public string TransactionId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int? BookingMinhNdaid { get; set; }

    public virtual BookingMinhNDA BookingMinhNda { get; set; }
}