// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATestServiceManager.Repositories.AnhTHQ.Models;

public partial class KitDeliveryNguyenTq
{
    public int KitDeliveryNguyenTqid { get; set; }

    public int? BookingMinhNdaid { get; set; }

    public string KitCode { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public bool? IsDelivered { get; set; }

    public string CourierOut { get; set; }

    public string TrackingNumberOut { get; set; }

    public string DeliveryStatusOut { get; set; }

    public string DeliveryNoteOut { get; set; }

    public DateTime? ReturnDate { get; set; }

    public bool? IsReturned { get; set; }

    public string CourierIn { get; set; }

    public string TrackingNumberIn { get; set; }

    public string DeliveryStatusIn { get; set; }

    public string ReturnReason { get; set; }

    public string DeliveryNoteIn { get; set; }

    public bool? DamageReported { get; set; }

    public decimal? Fee { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? IsExpressDelivery { get; set; }

    public virtual BookingMinhNDA BookingMinhNda { get; set; }

    public virtual ICollection<FeedbackNguyenTq> FeedbackNguyenTqs { get; set; } = new List<FeedbackNguyenTq>();
}