// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATestServiceManager.Repositories.AnhTHQ.Models;

public partial class SampleTestResultNhanTtt
{
    public int SampleTestResultNhanTttid { get; set; }

    public int? SampleNhanTttid { get; set; }

    public string GenLocus { get; set; }

    public string AlenOne { get; set; }

    public string AlenTwo { get; set; }

    public bool? IsMatched { get; set; }

    public string Note { get; set; }

    public virtual SampleNhanTtt SampleNhanTtt { get; set; }
}